### PR TITLE
Fixes for dbus 1.0

### PR DESCRIPTION
**Pull request by ijaketak**
for #346

### CODE REVIEW

**Comment by jaor** [comment]
@ijaketak thanks a lot, this looks mostly good.  the only glitch is that the build fails for ghc 7.8: seems that dbus 1.0 doesn't even compile for that ghc 7.8.  if so, perhaps we could use preprocessor conditionals, althought it sounds kind of messy... what do you think?

**Comment by peti** [comment]
Ping? Please release this fix soon'ish. Support for ghc 7.8.x really sounds like it's not *that* important, to be honest.

**Comment by jaor** [comment]
On Tue, Jul 10 2018, Peter Simons wrote:

> Ping? Please release this fix soon'ish. Support for ghc 7.8.x really
> sounds like it's not that important, to be honest.

Well, that depends on how the maintainers in several linux distributions feel
about it.  An option here is do the work to maintain both versions, if
this is urgent.

**Comment by jaor** [comment]
Sorry, sent too quickly... Personally, i have no real interest in ghc 7.8, but i wouldn't like to break other people's builds... also, i am not really sure what dbus-1.0 brings to the table for us over previous versions: is it fixing something important?

**Comment by peti** [comment]
dbus-1.x is part of both Stackage LTS 12.x and Nightly, which is the standard many distributions such as NixOS and openSUSE follow. If xmobar does not support it, then it's impossible to build the package in those environments.

**Comment by jaor** [comment]
@peti Many thanks for the clarification.  I've pushed a PR similar to this one that makes xmobar use dbus 1.x and drops compatibility with GHC 7.x.  @ijaketak thanks a lot for the PR! Closing manually.

**Comment by peti** [comment]
Thank you very much for the new release!

**Pull request closed without merging**
