### PR TITLE
Text mode for output

### PR DESCRIPTION
**Pull request by jaor**
Supporting colour escapes.  See discussion in #601

### CODE REVIEW

**Comment by jaor** [comment]
@pavel-the-best, i added a bit of documentation, and i'd say this can
be merged in master: what do you think?

**Comment by pavel-the-best** [comment]
> @pavel-the-best, i added a bit of documentation, and i'd say this can be merged in master: what do you think?

I think that adding command-line option that controls color format would be nice, but config file can be specified through command line, so that's no big deal. Other than that I agree this can be merged.

Is the test failure normal?

**Comment by jaor** [comment]
@pavel-the-best seems the test failure was some transitory glitch, it's working now.  btw, i was trying to put xmobar -T as swaybar's status_command, but it's not showing anything (things work fine in a terminal, with Pango):  what's your snippet in sway's config?

**Comment by jaor** [comment]
ah, i made it work with waybar :) with json output via

```shell
xmobar-exwm -T | jq --unbuffered --compact-output -R '{text: .}'
```

**Comment by pavel-the-best** [comment]
My swaybar config looks like this (inside of usual sway config)
```
bar {
    # font stuff
    status_command xmobar -T
    pango_markup enabled
    # color stuff
}
```

**Comment by jaor** [comment]
On Tue, Feb 01 2022, Pavel Kalugin wrote:

> My swaybar config looks like this (inside of usual sway config)
> ```
> bar {
>     # font stuff
>     status_command xmobar -T
>     pango_markup enabled
>     # color stuff
> }
> ```

hmmm, i've tried many variations of essentially that, and i cannot make
swaybar display my output.  perhaps it's related with something in the
xmobar template (e.g., i'm using emoji chars)... would you mind sharing
your template?

**Comment by pavel-the-best** [comment]
```
Config { font = "-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*"
       , additionalFonts = []
       , borderColor = "black"
       , border = TopB
       , bgColor = "#323232"
       , fgColor = "white"
       , alpha = 240
       , position = TopW L 90
       , textOffset = -1
       , iconOffset = -1
       , lowerOnStart = True
       , pickBroadest = False
       , persistent = False
       , hideOnStart = False
       , iconRoot = "."
       , allDesktops = True
       , overrideRedirect = True
       , textOutputColors = Pango
       , commands = [ Run Network "wg0" ["-L","0","-H","32",
                                         "--normal","lightgreen","--high","red",
                                         "-t","<dev>: <up>"] 10
                    , Run Wireless "wlo1" ["-L","50","-H","70",
                                           "--low","red","--normal","yellow",
                                           "--high","lightgreen"] 10
                    , Run BatteryP ["BAT1"] ["-t", "<acstatus> <watts>, <left>% / <timeleft>",
                                             "-L", "10", "-H", "80", "-l", "red",
                                             "-h", "lightgreen",
                                             "-a", "notify-send -u critical 'Battery running out!!"] 100
                    , Run Cpu ["-L","3","-H","50",
                               "--normal","lightgreen","--high","red"] 10
                    , Run Memory ["-t","Mem: <usedratio>%"] 10
                    , Run Date "%a %_d %b %Y %H:%M:%S %Z" "date" 10
                    , Run CoreTemp ["-L", "60", "-H", "80", "-l", "lightblue", "-n", "gray90", "-h", "red"] 50
                    , Run DiskU [("/home", "/home: <free>"), ("/", "/: <free>")] ["-L", "2", "-l", "red"] 20
                    ]

       , sepChar = "%"
       , alignSep = "}{"
       , template = "}{ %coretemp% | %cpu% | %memory% | %wg0% - %wlo1wi% }\
                    \{ <fc=yellow>%date%</fc> | %battery% | %disku%"
}
```

**Comment by jaor** [comment]
thank you.  turns out i had a problem with font specs in my sway
config somewhere, and asking explicitly for swaybar's font fixed the
problem: i can now see my xmobar just fine in sway! that's pretty rad,
and i'll investigate a bit more swaybar-protocol, maybe we can add
functionality and offer a full-featured status bar (for instance,
transparency components for colors come immediately to mind).

before that, i'm pushing a patch that adds the possibility to specify
the color format in the command line (`-TNoColors`, `-TPango`,
`-TAnsi`), while accepting also `-T`, which will use whatever's in the
configuration.  i'm thinking NoColors would be a better default there.

**Pull request merged**
