### PR TITLE
Fix CI dbus

### PR DESCRIPTION
**Pull request by sahabi**
This PR covers the PRs [331](https://github.com/jaor/xmobar/pull/331) and [332](https://github.com/jaor/xmobar/pull/332)

### CODE REVIEW

**Comment by jaor** [comment]
thanks a lot for looking at this, @sahabi ... seems we're good for ghc 7.6, but 7.4 is still complaining... i've been using 8.x for so long that i don't remember when 7.4 was active, so i am not sure if we need to work hard on it :)

**Comment by sahabi** [comment]
no problem, @joar. How about keeping the test for 7.6, remove 7.4 and add tests for 8.x?

**Comment by jaor** [comment]
> no problem, @joar. How about keeping the test for 7.6, remove 7.4 and add tests for 8.x?

sounds good to me... i wasn't aware there's 8.x in travis?

**Comment by sahabi** [comment]
> sounds good to me... i wasn't aware there's 8.x in travis?

According to https://serokell.io/posts/ru/2018-01-24-using-travis-CI-for-Haskell-projects.html 8.x is installed but not documented. Never tried myself.

**Comment by joar** [comment]
Hey, i'm @joar

**Pull request closed without merging**
