### PR TITLE
volume: allow alsa capture devices to be monitored

### PR DESCRIPTION
**Pull request by nlewo**
For instance, the following command can be used in the configuration
file:
  Run Volume "default" "Capture" [] 10

### CODE REVIEW

**Comment by jaor** [comment]
the code looks okay, but at least for me it's not fully working: i cannot see the volume of my capture device (the status seems fine, though).  perhaps it's some quirk in my sound configuration...

**Comment by nlewo** [comment]
sorry @jaor , I forgot to mention this related PR https://github.com/ttuegel/alsa-mixer/pull/5 which fixes a bug in alsa-mixer!

**Comment by jaor** [comment]
ah, ok... so we'd better wait until that fixed is merged and released in
alsa-mixer, so that we can ugrade our dependency accordingly.

**Comment by nlewo** [comment]
Sure. I will ping you when this fix is released.

**Comment by jaor** [comment]
thanks!

**Comment by ttuegel** [comment]
The fix has been released in alsa-mixer-0.2.0.3.

**Comment by jaor** [comment]
excellent. i've updated xmobar's dependencies and merged this pr. thanks!

**Pull request merged**
