### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by parvmor**

### CODE REVIEW

**Comment by jaor** [comment]
@parvmor hm, the option is actually `m`, or so the code says: what makes you think it's an `n`?

**Comment by parvmor** [comment]
The [code](https://github.com/jaor/xmobar/blob/master/src/Plugins/Monitors/Common.hs#L177) says that normal color's short flag is `n`. `m` is for minWidth.

**Comment by jaor** [comment]
@parvmor that's not the same flag.  the flag you mention is documented [here](https://github.com/jaor/xmobar/blob/master/readme.md#default-monitor-arguments).

For the Battery monitor there are *additional*  flags that come after the special "--" marker. `-m` is one of them, and it's implemented [here](https://github.com/jaor/xmobar/blob/master/src/Plugins/Monitors/Batt.hs#L71).  There's an example of its usage just a bit below the lines your PR touches.

**Comment by parvmor** [comment]
Ahh okay. I might have misplaced `-m` while configuring the rc.

**Pull request closed without merging**
