### PR TITLE
De-ambiguify TimeLocale when DateZone is enabled

### LINKED ISSUE #225: DateZone: Cannot build: Ambiguous occurrence ‘TimeLocale’
This is a fresh checkout. *GHC 7.10.1* and *time 1.5.0.1*.
```
$ git clone https://github.com/jaor/xmobar.git
$ cd xmobar
$ cabal install --flags="all_extensions" --allow-newer time
Resolving dependencies...
Configuring xmobar-0.23...
Building xmobar-0.23...
Failed to install xmobar-0.23
Build log ( /home/andrea/.cabal/logs/xmobar-0.23.log ):
Configuring xmobar-0.23...
Building xmobar-0.23...
Preprocessing executable 'xmobar' for xmobar-0.23...
[ 1 of 58] Compiling XPMFile          ( dist/build/xmobar/xmobar-tmp/XPMFile.hs, dist/build/xmobar/xmobar-tmp/XPMFile.o )
[ 2 of 58] Compiling StatFS           ( dist/build/xmobar/xmobar-tmp/StatFS.hs, dist/build/xmobar/xmobar-tmp/StatFS.o )
[ 3 of 58] Compiling IWlib            ( dist/build/xmobar/xmobar-tmp/IWlib.hs, dist/build/xmobar/xmobar-tmp/IWlib.o )
[ 4 of 58] Compiling Actions          ( src/Actions.hs, dist/build/xmobar/xmobar-tmp/Actions.o )
[ 5 of 58] Compiling Localize         ( dist/build/xmobar/xmobar-tmp/Localize.hs, dist/build/xmobar/xmobar-tmp/Localize.o )
[ 6 of 58] Compiling MinXft           ( dist/build/xmobar/xmobar-tmp/MinXft.hs, dist/build/xmobar/xmobar-tmp/MinXft.o )
[ 7 of 58] Compiling ColorCache       ( src/ColorCache.hs, dist/build/xmobar/xmobar-tmp/ColorCache.o )
[ 8 of 58] Compiling Plugins.Utils    ( src/Plugins/Utils.hs, dist/build/xmobar/xmobar-tmp/Plugins/Utils.o )
[ 9 of 58] Compiling Signal           ( src/Signal.hs, dist/build/xmobar/xmobar-tmp/Signal.o )
[10 of 58] Compiling IPC.DBus         ( src/IPC/DBus.hs, dist/build/xmobar/xmobar-tmp/IPC/DBus.o )
[11 of 58] Compiling Paths_xmobar     ( dist/build/autogen/Paths_xmobar.hs, dist/build/xmobar/xmobar-tmp/Paths_xmobar.o )
[12 of 58] Compiling XUtil            ( dist/build/xmobar/xmobar-tmp/XUtil.hs, dist/build/xmobar/xmobar-tmp/XUtil.o )
[13 of 58] Compiling Commands         ( src/Commands.hs, dist/build/xmobar/xmobar-tmp/Commands.o )
[14 of 58] Compiling Plugins          ( src/Plugins.hs, dist/build/xmobar/xmobar-tmp/Plugins.o )
[15 of 58] Compiling Plugins.Date     ( src/Plugins/Date.hs, dist/build/xmobar/xmobar-tmp/Plugins/Date.o )
[16 of 58] Compiling Plugins.PipeReader ( src/Plugins/PipeReader.hs, dist/build/xmobar/xmobar-tmp/Plugins/PipeReader.o )
[17 of 58] Compiling Plugins.BufferedPipeReader ( src/Plugins/BufferedPipeReader.hs, dist/build/xmobar/xmobar-tmp/Plugins/BufferedPipeReader.o )
[18 of 58] Compiling Plugins.MarqueePipeReader ( src/Plugins/MarqueePipeReader.hs, dist/build/xmobar/xmobar-tmp/Plugins/MarqueePipeReader.o )
[19 of 58] Compiling Plugins.CommandReader ( src/Plugins/CommandReader.hs, dist/build/xmobar/xmobar-tmp/Plugins/CommandReader.o )
[20 of 58] Compiling Plugins.StdinReader ( src/Plugins/StdinReader.hs, dist/build/xmobar/xmobar-tmp/Plugins/StdinReader.o )
[21 of 58] Compiling Plugins.Mail     ( src/Plugins/Mail.hs, dist/build/xmobar/xmobar-tmp/Plugins/Mail.o )
[22 of 58] Compiling Plugins.MBox     ( src/Plugins/MBox.hs, dist/build/xmobar/xmobar-tmp/Plugins/MBox.o )
[23 of 58] Compiling Plugins.DateZone ( src/Plugins/DateZone.hs, dist/build/xmobar/xmobar-tmp/Plugins/DateZone.o )

src/Plugins/DateZone.hs:76:19:
    Ambiguous occurrence ‘TimeLocale’
    It could refer to either ‘Data.Time.Format.TimeLocale’,
                             imported from ‘Data.Time.Format’ at src/Plugins/DateZone.hs:35:1-23
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.TimeLocale’,
                             imported from ‘System.Locale’ at src/Plugins/DateZone.hs:39:23-32

src/Plugins/DateZone.hs:79:23:
    Ambiguous occurrence ‘TimeLocale’
    It could refer to either ‘Data.Time.Format.TimeLocale’,
                             imported from ‘Data.Time.Format’ at src/Plugins/DateZone.hs:35:1-23
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.TimeLocale’,
                             imported from ‘System.Locale’ at src/Plugins/DateZone.hs:39:23-32
cabal: Error: some packages failed to install:
xmobar-0.23 failed during the building phase. The exception was:
ExitFailure 1
```

### PR DESCRIPTION
**Pull request by edwtjo**
Fixes #225 

It seems I forgot to compile xmobar with all plugins, of course DateZone was disabled.

### CODE REVIEW

**Comment by jaor** [comment]
@edwtjo this doesn't compile for me with GHC 7.6:

```
src/Plugins/DateZone.hs:41:26:
    Module `Data.Time.Format' does not export `TimeLocale'
Failed to install xmobar-0.23
```

**Comment by edwtjo** [comment]
Woops, silly mistake! How about now?

**Comment by jaor** [comment]
works like a charm, merged!

**Comment by edwtjo** [comment]
Perhaps a minor version bump to hackage to celebrate? :)

**Comment by jaor** [comment]
https://github.com/jaor/xmobar/releases/tag/0.23.1  :)

**Comment by edwtjo** [comment]
\o/ Thanks!

**Pull request closed without merging**
