### PR TITLE
Allow latest GHC

### PR DESCRIPTION
**Pull request by vmchale**
Bump to allow GHC 8.8.1

### CODE REVIEW

**Comment by jaor** [comment]
thanks, @vmchale ... from the travis build, it seems we have some other dependency to be updated, but i am not sure which one: https://travis-ci.org/jaor/xmobar/jobs/597856087 . any ideas? (sorry, right now i don't have a 8.8 installation handy).

**Comment by vmchale** [comment]
It seems to be something related to `cabal-install` 2.0 unfortunately. It works fine with `cabal-install` 2.2. 

Either we could disable the CI for 8.8, or it could be fixed to use a more modern `cabal-install`.

**Comment by jaor** [comment]
> Either we could disable the CI for 8.8, or it could be fixed to use a
> more modern cabal-install.

do you know if the latter would be complex? i'd prefer not disabling it,
but if fixing it gives us too much trouble we might as well wait until
travis uses it.

**Comment by vmchale** [comment]
I'll try to use cabal-install 2.2 in CI; it seems to work now?

**Comment by jaor** [comment]
excellent! thanks a lot for taking care of this.  rebased and merged!

**Pull request merged**
